#include "application/application.h"
#include "core/game_context.h"
#include "core/window.h"
#include "runtime/main_loop.h"

#include "base/containers/inplace_vector.h"
#include "base/io/filesystem.h"
#include "base/threads/job_system.h"

#include "render/camera.h"
#include "render/core/buffer_utils.h"
#include "render/core/command_utils.h"
#include "render/core/image_utils.h"
#include "render/environment/environment.h"
#include "render/material/material.h"
#include "render/model/mesh.h"
#include "render/shader/shader_compiler.h"
#include "render/shader/shader_declaration.h"
#include "render/shader/shader_manager.h"
#include "render/shader/shader_permutation.h"
#include "render/systems/pipeline_cache.h"
#include "render/systems/sampler_state_cache.h"

#include "render/render_graph/render_graph.h"
#include "render/render_graph/render_graph_blackboard.h"
#include "render/render_graph/render_graph_builder.h"
#include "render/render_graph/render_graph_utils.h"

#include "render/state_manager/camera_state_manager.h"
#include "render/state_manager/imgui_state_manager.h"
#include "render/state_manager/light_state_manager.h"
#include "render/state_manager/renderer_settings_state_manager.h"
#include "render/state_manager/state_manager_coordinator.h"
#include "render/state_manager/static_mesh_state_manager.h"
#include "render/state_manager/transform_state_manager.h"

#include "render_core/rhi/acceleration_structure.h"
#include "render_core/rhi/command_buffer.h"
#include "render_core/rhi/device_memory_allocator.h"
#include "render_core/rhi/framebuffer.h"
#include "render_core/rhi/pipeline.h"
#include "render_core/rhi/resource_group.h"
#include "render_core/rhi/resource_view.h"
#include "render_core/rhi/rhi_helpers.h"
#include "render_core/rhi/sampler_state.h"
#include "render_core/rhi/shader.h"
#include "render_core/rhi/swapchain.h"
#include "render_core/rhi/synchronization.h"

#include "scene/entity.h"
#include "scene/scene.h"

#include "state_manager/base_state_manager.h"
