#include "application/application.h"
#include "application/main_loop.h"
#include "application/window.h"

#include "base/containers/inplace_vector.h"
#include "base/io/filesystem.h"
#include "base/threads/job_system.h"

#include "renderer/camera.h"
#include "renderer/environment/environment.h"
#include "renderer/material/material.h"
#include "renderer/model/mesh.h"
#include "renderer/shader/shader_compiler.h"
#include "renderer/shader/shader_declaration.h"
#include "renderer/shader/shader_manager.h"
#include "renderer/shader/shader_permutation.h"

#include "render_core/render_graph/render_graph.h"
#include "render_core/render_graph/render_graph_blackboard.h"
#include "render_core/render_graph/render_graph_builder.h"
#include "render_core/render_graph/render_graph_utils.h"

#include "render_core/resources/buffers.h"
#include "render_core/resources/cubemap.h"
#include "render_core/resources/texture.h"

#include "render_core/rhi/acceleration_structure.h"
#include "render_core/rhi/command_buffer.h"
#include "render_core/rhi/device_memory_allocator.h"
#include "render_core/rhi/framebuffer.h"
#include "render_core/rhi/pipeline.h"
#include "render_core/rhi/renderer.h"
#include "render_core/rhi/resource_group.h"
#include "render_core/rhi/resource_view.h"
#include "render_core/rhi/rhi_helpers.h"
#include "render_core/rhi/sampler_state.h"
#include "render_core/rhi/shader.h"
#include "render_core/rhi/swapchain.h"
#include "render_core/rhi/synchronization.h"

#include "scene/entity.h"
#include "scene/scene.h"

#include "state_manager/base_state_manager.h"
#include "state_manager/camera_state_manager.h"
#include "state_manager/imgui_state_manager.h"
#include "state_manager/light_state_manager.h"
#include "state_manager/renderer_settings_state_manager.h"
#include "state_manager/state_manager_coordinator.h"
#include "state_manager/static_mesh_state_manager.h"
#include "state_manager/transform_state_manager.h"
